export const initialEventFormState = {
  id: '',
  title: '',
  description: '',
  category: '',
  capacity: 200,
  attendeeCount: 0,
  type: 'IN_PERSON',
  dresscode: '',
  date: new Date(),
  time: '',
  duration: '',
  location: '',
  maxAttendees: null,
  status: 'UPCOMING',
  featured: false,
  host: '',
  requirements: '',
  materials: '',
  registrationUrl: '',
  meetingUrl: '',
  isPublic: true,
  requiresRSVP: false,
  registrationDeadline: new Date(),
  allowMultipleTickets: false,
  salesStartDate: null,
  salesEndDate: null,
  isUpdating: false,
  order: 0
}
