import { EventStatus, IEvent } from "@/types/entities/event";

export const initialEventConfig: IEvent = {
  id: "",
  createdAt: new Date(),
  updatedAt: new Date(),
  title: "",
  description: null,
  category: "",
  type: "",
  dresscode: null,
  date: new Date(),
  time: "",
  duration: "",
  location: "",
  maxAttendees: null,
  attendees: 0,
  status: EventStatus.UPCOMING,
  featured: false,
  host: null,
  requirements: null,
  materials: null,
  registrationUrl: null,
  meetingUrl: null,
  viewCount: 0,
  clickCount: 0,
  isPublic: true,
  requiresRSVP: false,
  registrationDeadline: new Date(),
  allowMultipleTickets: false,
  salesStartDate: new Date(),
  salesEndDate: new Date(),
  userId: "",
};
