import { IHero } from "@/types/entities/hero";

export const initialHeroConfig: IHero = {
  id: "",
  name: "New Hero",
  minHeight: "screen" as const, // Use 'as const' for literal types
  actualHeight: "100vh",
  backgroundType: "gradient" as const,
  backgroundColor: "#0a0a0a",
  gradientFrom: "#1e1b4b",
  gradientTo: "#0f172a",
  backgroundImage: "",
  backgroundVideo: "",
  backgroundFile: null,
  backgroundVideoFile: null,
  backgroundSize: "cover" as const,
  backgroundPosition: "center" as const,
  title: "Great Futures Start Here",
  titleColor: "#ffffff",
  titleGradientWord: "Futures",
  titleGradientFrom: "#6366f1",
  titleGradientTo: "#ec4899",
  titleUseGradient: false,
  titleAnimation: "fade-up" as const,
  titleLineHeight: "1.2",
  titleFontSize: "4rem",
  subtitle:
    "Inspiring and enabling all young people to realize their full potential",
  subtitleColor: "#a3a3a3",
  subtitleLineHeight: "1.5",
  subtitleFontSize: "1.5rem",
  subtitleAnimation: "fade-up" as const,
  ctaAnimation: "fade-up" as const,
  layout: "side-by-side" as const,
  showThermometer: false,
  thermometerGoal: 100000,
  thermometerCurrent: 45000,
  thermometerColor: "#6366f1",
  thermometerPosition: "right" as const,
  showCountdown: false,
  countdownDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0],
  countdownLabel: "Event Starts In",
  countdownPosition: "right" as const,
  countdownColor: "#6366f1",
  showGrowthTree: false,
  growthTreeCurrent: 8234,
  growthTreeGoal: 10000,
  growthTreeLabel: "Community Members",
  growthTreePosition: "right" as const,
  growthTreeColor: "#10b981",
  ctaText: "Parent Portal",
  ctaLink: "/",
  ctaBackgroundColor: "#6366f1",
  ctaTextColor: "#ffffff",
  ctaBorderRadius: "50",
  overlayOpacity: 0.5,
  showFloatingButton: false,
  floatingButtonText: "Get Help",
  floatingButtonPosition: "bottom-right" as const,
  floatingButtonBgColor: "#6366f1",
  floatingButtonTextColor: "#ffffff",
  floatingButtonBorderRadius: "9999",
  floatingButtonAnimation: "pulse" as const,
  floatingButtonAction: "modal" as const,
  floatingButtonLink: "/contact",
  floatingButtonIcon: "chat" as const,
  showTopBanner: false,
  topBannerText: "Click here to learn about our Capital Campaign",
  topBannerHeight: "40",
  topBannerBgColor: "#6366f1",
  topBannerTextColor: "#ffffff",
  topBannerFontSize: "0.875",
  topBannerBold: false,
  topBannerLinkType: "none",
  topBannerLink: "",
};
