export const initialProgramFormState = {
  id: '',
  name: '',
  description1: '',
  description2: undefined,
  description3: undefined,
  description4: undefined,
  description5: undefined,
  image: '',
  heroImage: '',
  showAgeGroup: false,
  dropOffStart: '',
  dropOffEnd: '',
  pickUpStart: '',
  pickUpEnd: '',
  datesAvailable: '',
  license: '',
  location: '',
  frequency: 'Weekly',
  ageGroup: '5-10',
  additionalDetails: [],
  themes: [],
  showThemes: false
}
