import {
  Rocket,
  User,
  Calendar,
  CreditCard,
  FileText,
  Bell,
  MessageSquare,
  Settings,
  Baby,
  GraduationCap,
  Heart,
  Clock,
  CheckCircle,
} from "lucide-react";

export const parentNavLinks = [
  {
    id: "flight-deck",
    label: "Flight Deck",
    icon: Rocket,
    description: "Dashboard Overview",
    linkKey: "/parent/flight-deck",
  },
  {
    id: "command-center",
    label: "Command Center",
    icon: User,
    description: "Complete Your Profile",
    linkKey: "/parent/command-center",
  },
  {
    id: "crew-roster",
    label: "Crew Roster",
    icon: Baby,
    description: "Manage Children",
    linkKey: "/parent/crew-roster",
  },
  {
    id: "launch-pad",
    label: "The Launch Pad",
    icon: GraduationCap,
    description: "Browse & Enroll",
    linkKey: "/parent/launch-pad",
  },
  {
    id: "active-missions",
    label: "Active Missions",
    icon: CheckCircle,
    description: "Active Enrollments",
    linkKey: "/parent/active-missions",
  },
  {
    id: "capsule",
    label: "The Capsule",
    icon: Calendar,
    description: "Upcoming Events",
    linkKey: "/parent/capsule",
  },
  {
    id: "fuel-station",
    label: "The Fuel Station",
    icon: CreditCard,
    description: "Payment History",
    linkKey: "/parent/fuel-station",
  },
  {
    id: "flight-schedule",
    label: "Flight Schedule",
    icon: Clock,
    description: "Program Schedule",
    linkKey: "/parent/flight-schedule",
  },
  {
    id: "communications",
    label: "Communications",
    icon: MessageSquare,
    description: "Messages",
    linkKey: "/parent/communications",
  },
  {
    id: "signal-tower",
    label: "Signal Tower",
    icon: Bell,
    description: "Alerts & Updates",
    linkKey: "/parent/signal-tower",
  },
  {
    id: "mission-files",
    label: "Mission Files",
    icon: FileText,
    description: "Forms & Waivers",
    linkKey: "/parent/mission-files",
  },
  {
    id: "ground-support",
    label: "Ground Support",
    icon: Heart,
    description: "Get Help",
    linkKey: "/parent/ground-support",
  },
  {
    id: "operations-panel",
    label: "Operations Panel",
    icon: Settings,
    description: "Account Settings",
    linkKey: "/parent/operations-panel",
  },
];
