import { IFeature } from "@/types/project-breakdown";
import {
  Badge,
  Calendar,
  ChartBar,
  Cloud,
  Cpu,
  CreditCard,
  Database,
  DatabaseIcon,
  Edit,
  Flame,
  FlaskConical,
  Gamepad,
  Heart,
  Languages,
  Layout,
  MessageSquare,
  QrCode,
  Rocket,
  Server,
  Shield,
  Star,
  Triangle,
  Users,
} from "lucide-react";

export const coreFeatures = [
  {
    icon: Rocket,
    title: "Modern Web Application Foundation",
    description:
      "Fast, responsive web app that works on all devices (phones, tablets, computers) with secure cloud hosting",
    hours: "6-8 hours",
    cost: "$490",
  },
  {
    icon: Layout,
    title: "Complete UI Design & Development",
    description:
      "Professional design and development of all frontend pages (home, about, programs, events, contact, user portals) and all backend admin pages (dashboard, user management, payments, communications, settings, etc.) with custom UI/UX, responsive layouts, interactive components, custom drawers, modals, and forms",
    hours: "20-30 hours",
    cost: "$400",
  },

  {
    icon: Shield,
    title: "Simple & Secure Login System",
    description:
      "Easy sign-in with Google accounts or magic email links (no passwords needed!), different access levels for staff, parents, and youth members",
    hours: "5-6 hours",
    cost: "$385",
  },
  {
    icon: Database,
    title: "Secure Data Storage & Backup",
    description:
      "Professional cloud database that stores all member information safely with automatic backups and fast performance",
    hours: "3-4 hours",
    cost: "$245",
  },
];

export const requiredThirdPartyServices = [
  {
    icon: Server,
    title: "Railway",
    description:
      "Cloud-based backend hosting for databases, serverless functions, and environment management",
    hours: "—",
    cost: "Varies by usage",
  },
  {
    icon: Triangle,
    title: "Vercel",
    description:
      "High-performance hosting for your Next.js frontend with built-in CI/CD and global edge network",
    hours: "—",
    cost: "Varies by usage",
  },
  {
    icon: Flame,
    title: "Google Firebase",
    description:
      "Authentication, file storage, and real-time services used for secure user accounts and app functionality",
    hours: "—",
    cost: "Varies by usage",
  },
  {
    icon: Languages,
    title: "Weglot",
    description:
      "Professional translation service for multilingual support with automatic detection and language routing. 3 translated languages - 50,000 words",
    hours: "—",
    cost: "$35",
  },
];

export const additionalFeatures: IFeature[] = [
  {
    id: "content-management",
    system: "Mission Control",
    icon: Edit,
    title: "Admin Operations Panel",
    description:
      "Admin panel to manage ALL website content, members, programs, payments, and donations, events — no coding needed.",
    details: [
      "Analytics & Reporting dashboard shell (The Observatory module required)",
      "Staff & Board of Directors management (The Nebula module required)",
      "Program Hub – modern, concise, central place for all program actions.",
      "Create and update news articles displayed on the website",
      "Newsletter system to capture emails for admin review and export",
      "Contact form submissions for admin review and follow-up",
      "Employment applications tracking",
      "Volunteer applications management",
      "Resource links management",
      "Awards & recognition management (Honorees, Youth of the Year, etc.)",
      "View and manage all parent sign-ups (The Family Launch Station module required)",
      "Access all child profiles linked to parents",
      "Track program registrations",
      "Monitor payments and billing for members and programs (The Credit Orb module required)",
      "View and manage donation history and donor info (Fundraising & Donor Portal module required)",
    ],
    hours: "45-60 hours",
    cost: 3640,
  },
  {
    id: "parent-portal",
    system: "The Family Launch Station",
    icon: Users,
    title: "Complete Parent & Family Portal",
    description:
      "Full-featured portal where parents manage their children's club experience, communicate with staff, and stay engaged.",
    details: [
      "Parent snapshot dashboard",
      "Complete parent profile",
      "Multiple child profiles",
      "Program enrollment & waitlists",
      "Digital permission slips",
      "Billing statements & receipts (The Credit Orb required)",
      "Payment processing (The Credit Orb required)",
      "Direct messaging with staff (Multi-Channel Communication System required)",
      "Emergency contact management",
      "Pick-up authorization",
      "Document uploads (vaccination, etc.) (Media Storage & Management System)",
      "Push notifications for updates (Multi-Channel Communication module required)",
    ],
    hours: "110-130 hours",
    cost: 8400,
  },

  {
    id: "youth-portal",
    system: "The Launch Pad",
    icon: Rocket,
    title: "Youth Member Portal",
    description:
      "A fun digital hub where kids explore activities, track their progress, and connect with friends in their club crew.",
    details: [
      "Custom profile with stats and mission logs (The Nebula required)",
      "Custom dashboard with visual progress tracking",
      "Galactic game center with educational space-themed mini-games (The Astro Deck required)",
      "Achievement constellation for collecting cosmic badges (The Badge Bay required)",
      "Crew connections to form squads and see active members",
      "Daily and weekly cosmic challenges with bonus rewards",
      "Digital space gallery for showcasing artwork and projects (The Nebula required)",
      "Share updates, photos, and achievements in a moderated member feed (The Nebula required)",
    ],
    hours: "60-80 hours",
    cost: 4900,
  },
  {
    id: "hero-studio",
    system: "The Orbital Deck",
    icon: Star, // replace with your icon component
    title: "Hero Studio & Campaign Visuals",
    description:
      "Create dynamic hero sections for campaigns, events, and fundraising with pre-built interactive components.",
    details: [
      "Drag-and-drop hero builder with pre-built components",
      "Configurable thermometer/progress bar for fundraising goals",
      "Set target amounts and track live progress",
      "Add call-to-action buttons and links",
      "Dynamic text and image sections",
      "Embed videos, images, or animated assets (The Nebula required)",
      "Mobile-friendly and responsive layouts",
      "Preview before publishing",
    ],
    hours: "40-50 hours",
    cost: 4500,
  },
  {
    id: "check-in-system",
    system: "The Mission Gate",
    icon: QrCode,
    title: "Digital Check-In/Out System",
    description:
      "Secure system for tracking attendance with parent notifications.",
    details: [
      "PIN check-in (Youth Portal required)",
      "Photo verification (Supabase + Edge Function calling an AI service (AWS Rekognition, Azure Face API))",
      "Real-time parent alerts (Multi-Channel Communication module required)",
      "Authorized pickup list",
      "Late pickup notifications",
      "Daily attendance reports",
    ],
    hours: "50-60 hours",
    cost: 3850,
  },
  {
    id: "communication-hub",
    system: "The Comm Station",
    icon: MessageSquare,
    title: "Multi-Channel Communication System",
    description:
      "Centralized communication between staff, parents, and members.",
    details: [
      "Push notifications",
      "In-app messaging (Supabase Realtime)",
      "Emergency broadcasts (via Resend email service)",
      "Translation services (continuing to use Weglot)",
    ],
    hours: "26-32 hours",
    cost: 2030,
  },
  {
    id: "historical-data-migration",
    system: "The Black Hole",
    icon: DatabaseIcon, // replace with your icon component
    title: "Historical Data Migration",
    description:
      "Completely import and preserve all historical program, attendance, member, and content data into the new system, ensuring accuracy and integrity.",
    details: [
      "Transfer all past attendance records",
      "Migrate member profiles",
      "Migrate historical program and event data",
      "Migrate media library, documents, and uploads",
      "Validate data integrity during migration",
      "Map legacy data to new CMS structure",
      "Test migrated data for accuracy and completeness",
    ],
    hours: "100-120 hours",
    cost: 7700,
  },
  {
    id: "reporting-analytics",
    system: "The Observatory",
    icon: ChartBar,
    title: "Analytics & Reporting Dashboard",
    description:
      "Comprehensive data insights for program effectiveness and club operations.",
    details: [
      "Track attendance trends (Digital Check-In/Out required)",
      "See program popularity and participation rates at a glance",
      "Snapshot of member demographics: age, grade, location",
      "Quickly generate custom reports for programs, events, or memberships",
      "Export reports in CSV, PDF, or Excel for further analysis",
      "Monitor revenue from events, donations, and program fees in real-time",
      "Compare current metrics with historical data for trend insights",
      "Visual dashboards with charts, graphs, and key performance indicators (KPIs)",
    ],
    hours: "25-30 hours",
    cost: 2100,
  },
  {
    id: "donor-management",
    system: "The Starforge",
    icon: Heart,
    title: "Fundraising & Donor Portal",
    description: "Track donations and manage donor relationships.",
    details: [
      "Online donation forms (The Credit Orb required)",
      "Set up and manage recurring donations for members and supporters",
      "Maintain a detailed donor database with contact info and giving history",
      "Track fundraising campaigns, goals, and progress in real-time",
      "Automated thank-you messages and acknowledgments for donors",
      "Export donor and campaign data for reporting or CRM integration",
      "Segment donors by giving level, campaign, or engagement for targeted outreach",
    ],
    hours: "24-34 hours",
    cost: 1960,
  },
  {
    id: "media-storage",
    system: "The Nebula",
    icon: Cloud,
    title: "Media Storage & Management System",
    description:
      "Centralized storage for videos, documents, and images using Firebase Storage.",
    details: [
      "Upload and organize videos, documents, and images",
      "Secure access control for different user roles",
      "Automatic backup and cloud hosting",
      "Direct integration with CMS and communication modules",
      "Optimized media delivery for web and mobile",
    ],
    hours: "15-20 hours",
    cost: 1190,
  },
  {
    id: "payment-processing",
    system: "The Credit Orb",
    icon: CreditCard,
    title: "Payment & Billing System",
    description:
      "Process program fees, memberships, and other payments online.",
    details: [
      "Seamless Stripe integration for secure online payments",
      "Automated program fee collection with support for single or recurring payments",
      "Manage and process refunds directly from the admin dashboard",
      "Generate detailed financial reports by program, date, or member",
      "Track outstanding balances and payment history for each member",
      "Integrate with event registrations and donations for consolidated reporting",
    ],
    hours: "35-45 hours",
    cost: 3100,
  },
  {
    id: "achievement-badges",
    system: "The Badge Bay",
    icon: Badge, // replace with your icon component
    title: "Achievement Badge & Gamification System",
    description:
      "Reward members with badges, points, and levels for participation, engagement, and achievements.",
    details: [
      "Earn badges for program milestones",
      "Track points and levels in parent/youth portal",
      "Leaderboards for friendly competition",
      "Display top achievers in Hero Studio (Hero Studio required)",
      "Motivates engagement and participation",
    ],
    hours: "30-40 hours",
    cost: 2450,
  },
  {
    id: "space-lab",
    system: "The Code Lab",
    icon: FlaskConical,
    title: "Space Lab: Experiments & Challenges",
    description:
      "Interactive coding lessons and space-themed programming challenges for members to explore and learn technology skills.",
    details: [
      "Step-by-step coding lessons using beginner-friendly languages",
      "Gamified challenges to practice coding concepts",
      "Track completed challenges and badges (Achievement Badge System required)",
      "Submit code projects or screenshots to portal for staff review (The Nebula required)",
      "Weekly or monthly featured coding missions",
      "Optional integration with Hero Studio to showcase top coding projects (The Orbital Deck required)",
    ],
    hours: "18-22 hours",
    cost: 1650,
  },
  {
    id: "event-management",
    system: "The Orbital Hall",
    icon: Calendar,
    title: "Event Planning & Registration",
    description:
      "Manage special events with online registration, ticketing, and itemized purchases.",
    details: [
      "Payment processing integration (The Credit Orb required)",
      "Event creation and management tools",
      "Online registration and ticketing",
      "Assign purchasable items (e.g., tables, VIP packages)",
      "Inventory and capacity management",
      "Waitlist handling",
      "Follow-up surveys and feedback collection",
      "Custom pricing per item or ticket type",
      "Automated confirmation emails and receipts (Multi-Channel Communication System)",
    ],
    hours: "30-50 hours",
    cost: 2800,
  },
  {
    id: "game-center",
    system: "The Astro Arcade",
    icon: Gamepad,
    title: "Game Center",
    description:
      "A space-themed hub for interactive games, challenges, and skill-building fun.",
    details: [
      "Play educational space-themed games that teach science, math, and problem-solving",
      "Track personal high scores and progress through missions",
      "Compete in friendly challenges with other club members",
      "Earn digital badges and rewards for completing games and challenges",
      "Explore mini-games tied to club activities and learning programs",
      "Access seasonal or event-based space missions for extra fun",
    ],
    hours: "60-80 hours",
    cost: 4900,
  },
  {
    id: "ai-integration",
    system: "Mother",
    icon: Cpu,
    title: "AI Integration & Smart Assistance",
    description:
      "Mother acts as the central AI brain of the club platform, assisting admins, staff, parents, and youth with intelligent automation and insights.",
    details: [
      "AI-driven suggestions for program scheduling, attendance, and capacity planning",
      "Smart reminders and notifications for parents and members",
      "Automated report generation and data insights for admins",
      "AI-assisted content recommendations for news, events, and Hero Studio campaigns",
      "Predictive analytics for donation trends, program popularity, and volunteer engagement",
      "Real-time chat assistance for users across the portal, powered by AI",
      "Integration with all existing modules to streamline workflows and reduce manual tasks",
    ],
    hours: "80-100 hours",
    cost: 6200,
  },
];
